//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaKutuphaneApp.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdaKutuphaneEntities1 : DbContext
    {
        public AdaKutuphaneEntities1()
            : base("name=AdaKutuphaneEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblCezalar> tblCezalar { get; set; }
        public virtual DbSet<tblHareketler> tblHareketler { get; set; }
        public virtual DbSet<tblKasa> tblKasa { get; set; }
        public virtual DbSet<tblKategoriler> tblKategoriler { get; set; }
        public virtual DbSet<tblKitaplar> tblKitaplar { get; set; }
        public virtual DbSet<tblPersoneller> tblPersoneller { get; set; }
        public virtual DbSet<tblUyeler> tblUyeler { get; set; }
        public virtual DbSet<tblYazarlar> tblYazarlar { get; set; }
    }
}
