//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaKutuphaneApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCezalar
    {
        public int ID { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<int> HAREKET { get; set; }
        public Nullable<System.DateTime> BASLANGIC { get; set; }
        public Nullable<System.DateTime> BITIS { get; set; }
        public Nullable<decimal> CEZA { get; set; }
    
        public virtual tblHareketler tblHareketler { get; set; }
        public virtual tblUyeler tblUyeler { get; set; }
    }
}
