//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaKutuphaneApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKitaplar()
        {
            this.tblHareketler = new HashSet<tblHareketler>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public Nullable<int> YAZAR { get; set; }
        public string BASIMYILI { get; set; }
        public string YAYINEVİ { get; set; }
        public string SAYFASAYISI { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHareketler> tblHareketler { get; set; }
        public virtual tblKategoriler tblKategoriler { get; set; }
        public virtual tblYazarlar tblYazarlar { get; set; }
    }
}
